version: '3'

services:
  service-built:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./weights:/app/weights

  service-pulled:
    image: olegdayo/example-service:v1.0.1
    ports:
      - '8001:8000'
    volumes:
      - ./weights:/app/weights
