version: '3'

services:
  nano:
    build: .
    command:
      - -w
      - /app/weights/yolov8n.pt
    ports:
      - '8000:8000'
    volumes:
      - ./weights:/app/weights

  small:
    build: .
    command:
      - -w
      - /app/weights/yolov8s.pt
    ports:
      - '8001:8000'
    volumes:
      - ./weights:/app/weights
