name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:

jobs:
  model-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Get repository and version  
        if: startsWith(github.ref, 'refs/tags')
        id: get_data
        run: |
            echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
            echo "REPOSITORY=github.com/${GITHUB_REPOSITORY}" >> $GITHUB_OUTPUT

      - name: Check model registry
        if: startsWith(github.ref, 'refs/tags')
        run: curl -f -i -X GET "http://64.225.73.53:8080/api/models/lookup?repository=${{ steps.get_data.outputs.REPOSITORY }}&version=${{ steps.get_data.outputs.VERSION }}"
